export const countriesArray = [
  {
    id: 1,
    name: "Afghanistan",
    iso: "af",
    capital: "Kabul",
    flag: "flags/af.svg",
    colors: ["black","red","green","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 2,
    name: "Albania",
    iso: "al",
    capital: "Tirana",
    flag: "flags/al.svg",
    colors: ["red","black"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 3,
    name: "Algeria",
    iso: "dz",
    capital: "Algiers",
    flag: "flags/dz.svg",
    colors: ["green","white","red"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 4,
    name: "Andorra",
    iso: "ad",
    capital: "Andorra la Vella",
    flag: "flags/ad.svg",
    colors: ["blue","yellow","red"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 5,
    name: "Angola",
    iso: "ao",
    capital: "Luanda",
    flag: "flags/ao.svg",
    colors: ["red","black","yellow"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 6,
    name: "Antigua and Barbuda",
    iso: "ag",
    capital: "St. John's",
    flag: "flags/ag.svg",
    colors: ["red","black","yellow","white","blue"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 7,
    name: "Argentina",
    iso: "ar",
    capital: "Buenos Aires",
    flag: "flags/ar.svg",
    colors: ["white","blue","yellow"],
    hasSymbol: true,
    continent: "south-america",
  },
  {
    id: 8,
    name: "Armenia",
    iso: "am",
    capital: "Yerevan",
    flag: "flags/am.svg",
    colors: ["red","blue","yellow"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 9,
    name: "Australia",
    iso: "au",
    capital: "Canberra",
    flag: "flags/au.svg",
    colors: ["red","blue","white"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 10,
    name: "Austria",
    iso: "at",
    capital: "Vienna",
    flag: "flags/at.svg",
    colors: ["red","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 11,
    name: "Azerbaijan",
    iso: "az",
    capital: "Baku",
    flag: "flags/az.svg",
    colors: ["red","green","blue","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 12,
    name: "Bahamas",
    iso: "bs",
    capital: "Nassau",
    flag: "flags/bs.svg",
    colors: ["blue","black","yellow"],
    hasSymbol: false,
    continent: "north-america",
  },
  {
    id: 13,
    name: "Bahrain",
    iso: "bh",
    capital: "Manama",
    flag: "flags/bh.svg",
    colors: ["red","white"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 14,
    name: "Bangladesh",
    iso: "bd",
    capital: "Dhaka",
    flag: "flags/bd.svg",
    colors: ["red","green"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 15,
    name: "Barbados",
    iso: "bb",
    capital: "Bridgetown",
    flag: "flags/bb.svg",
    colors: ["blue","black","yellow"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 16,
    name: "Belarus",
    iso: "by",
    capital: "Minsk",
    flag: "flags/by.svg",
    colors: ["red","white","green"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 17,
    name: "Belgium",
    iso: "be",
    capital: "Brussels",
    flag: "flags/be.svg",
    colors: ["red","black","yellow"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 18,
    name: "Belize",
    iso: "bz",
    capital: "Belmopan",
    flag: "flags/bz.svg",
    colors: ["blue","red","white","green",],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 19,
    name: "Benin",
    iso: "bj",
    capital: "Porto-Novo",
    flag: "flags/bj.svg",
    colors: ["green","red","yellow"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 20,
    name: "Bhutan",
    iso: "bt",
    capital: "Thimphu",
    flag: "flags/bt.svg",
    colors: ["orange","white","yellow"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 21,
    name: "Bolivia",
    iso: "bo",
    capital: "Sucre",
    flag: "flags/bo.svg",
    colors: ["green","red","yellow"],
    hasSymbol: true,
    continent: "south-america",
  },
  {
    id: 22,
    name: "Bosnia and Herzegovina",
    iso: "ba",
    capital: "Sarajevo",
    flag: "flags/ba.svg",
    colors: ["blue","white","yellow"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 23,
    name: "Botswana",
    iso: "bw",
    capital: "Gaborone",
    flag: "flags/bw.svg",
    colors: ["blue","white","black"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 24,
    name: "Brazil",
    iso: "br",
    capital: "Brasília",
    flag: "flags/br.svg",
    colors: ["green","blue","yellow","white"],
    hasSymbol: true,
    continent: "south-america",
  },
  {
    id: 25,
    name: "Brunei Darussalam",
    iso: "bn",
    capital: "Bandar Seri Begawan",
    flag: "flags/bn.svg",
    colors: ["white","red","yellow","black"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 26,
    name: "Bulgaria",
    iso: "bg",
    capital: "Sofia",
    flag: "flags/bg.svg",
    colors: ["green","red","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 27,
    name: "Burkina Faso",
    iso: "bf",
    capital: "Ouagadougou",
    flag: "flags/bf.svg",
    colors: ["green","red","yellow"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 28,
    name: "Burundi",
    iso: "bi",
    capital: "Bujumbura",
    flag: "flags/bi.svg",
    colors: ["green","red","white"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 29,
    name: "Cabo Verde",
    iso: "cv",
    capital: "Praia",
    flag: "flags/cv.svg",
    colors: ["blue","red","yellow","white"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 30,
    name: "Cambodia",
    iso: "kh",
    capital: "Phnom Penh",
    flag: "flags/kh.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 31,
    name: "Cameroon",
    iso: "cm",
    capital: "Yaoundé",
    flag: "flags/cm.svg",
    colors: ["green","red","yellow"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 32,
    name: "Canada",
    iso: "ca",
    capital: "Ottawa",
    flag: "flags/ca.svg",
    colors: ["white","red"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 33,
    name: "Central african Republic",
    iso: "cf",
    capital: "Bangui",
    flag: "flags/cf.svg",
    colors: ["green","red","yellow","white","blue"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 34,
    name: "Chad",
    iso: "td",
    capital: "N'Djamena",
    flag: "flags/td.svg",
    colors: ["blue","red","yellow"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 35,
    name: "Chile",
    iso: "cl",
    capital: "Santiago",
    flag: "flags/cl.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "south-america",
  },
  {
    id: 36,
    name: "China",
    iso: "cn",
    capital: "Beijing",
    flag: "flags/cn.svg",
    colors: ["red","yellow"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 37,
    name: "Colombia",
    iso: "co",
    capital: "Bogotá",
    flag: "flags/co.svg",
    colors: ["blue","red","yellow"],
    hasSymbol: false,
    continent: "south-america",
  },
  {
    id: 38,
    name: "Comoros",
    iso: "km",
    capital: "Moroni",
    flag: "flags/km.svg",
    colors: ["green","red","yellow","white","blue"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 39,
    name: "Costa Rica",
    iso: "cr",
    capital: "San José",
    flag: "flags/cr.svg",
    colors: ["blue","red","white"],
    hasSymbol: false,
    continent: "north-america",
  },
  {
    id: 40,
    name: "Croatia",
    iso: "hr",
    capital: "Zagreb",
    flag: "flags/hr.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 41,
    name: "Cuba",
    iso: "cu",
    capital: "Havana",
    flag: "flags/cu.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 42,
    name: "Cyprus",
    iso: "cy",
    capital: "Nicosia",
    flag: "flags/cy.svg",
    colors: ["green","white","orange"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 43,
    name: "Czech Republic",
    iso: "cz",
    capital: "Prague",
    flag: "flags/cz.svg",
    colors: ["blue","red","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 44,
    name: "Côte d'Ivoire",
    iso: "ci",
    capital: "Yamoussoukro",
    flag: "flags/ci.svg",
    colors: ["green","white","orange"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 45,
    name: "Democratic Republic of the Congo",
    iso: "cd",
    capital: "Kinshasa",
    flag: "flags/cd.svg",
    colors: ["blue","red","yellow"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 46,
    name: "Denmark",
    iso: "dk",
    capital: "Copenhagen",
    flag: "flags/dk.svg",
    colors: ["red","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 47,
    name: "Djibouti",
    iso: "dj",
    capital: "Djibouti",
    flag: "flags/dj.svg",
    colors: ["green","red","white","blue"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 48,
    name: "Dominica",
    iso: "dm",
    capital: "Roseau",
    flag: "flags/dm.svg",
    colors: ["green","red","yellow","white","black"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 49,
    name: "Dominican Republic",
    iso: "do",
    capital: "Santo Domingo",
    flag: "flags/do.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 50,
    name: "Ecuador",
    iso: "ec",
    capital: "Quito",
    flag: "flags/ec.svg",
    colors: ["blue","red","yellow"],
    hasSymbol: true,
    continent: "south-america",
  },
  {
    id: 51,
    name: "Egypt",
    iso: "eg",
    capital: "Cairo",
    flag: "flags/eg.svg",
    colors: ["red","white","black","gold"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 52,
    name: "El Salvador",
    iso: "sv",
    capital: "San Salvador",
    flag: "flags/sv.svg",
    colors: ["white","blue","gold"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 53,
    name: "Equatorial Guinea",
    iso: "gq",
    capital: "Malabo",
    flag: "flags/gq.svg",
    colors: ["red","white","green","blue"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 54,
    name: "Eritrea",
    iso: "er",
    capital: "Asmara",
    flag: "flags/er.svg",
    colors: ["red","green","blue","yellow"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 55,
    name: "Estonia",
    iso: "ee",
    capital: "Tallinn",
    flag: "flags/ee.svg",
    colors: ["white","black","blue"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 56,
    name: "Eswatini",
    iso: "sz",
    capital: "Lobamba, Mbabane",
    flag: "flags/sz.svg",
    colors: ["blue","red","white","black","yellow"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 57,
    name: "Ethiopia",
    iso: "et",
    capital: "Addis Ababa",
    flag: "flags/et.svg",
    colors: ["red","blue","green","yellow"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 58,
    name: "Federated States of Micronesia",
    iso: "fm",
    capital: "Palikir",
    flag: "flags/fm.svg",
    colors: ["blue","white"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 59,
    name: "Fiji",
    iso: "fj",
    capital: "Suva",
    flag: "flags/fj.svg",
    colors: ["blue","white","red"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 60,
    name: "Finland",
    iso: "fi",
    capital: "Helsinki",
    flag: "flags/fi.svg",
    colors: ["white","blue"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 61,
    name: "France",
    iso: "fr",
    capital: "Paris",
    flag: "flags/fr.svg",
    colors: ["red","white","blue"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 62,
    name: "Gabon",
    iso: "ga",
    capital: "Libreville",
    flag: "flags/ga.svg",
    colors: ["green","yellow","blue"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 63,
    name: "Gambia",
    iso: "gm",
    capital: "Banjul",
    flag: "flags/gm.svg",
    colors: ["red","blue","green","white"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 64,
    name: "Georgia",
    iso: "ge",
    capital: "Tbilisi",
    flag: "flags/ge.svg",
    colors: ["white","red"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 65,
    name: "Germany",
    iso: "de",
    capital: "Berlin",
    flag: "flags/de.svg",
    colors: ["black","red","yellow"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 66,
    name: "Ghana",
    iso: "gh",
    capital: "Accra",
    flag: "flags/gh.svg",
    colors: ["black","red","yellow","green"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 67,
    name: "Greece",
    iso: "gr",
    capital: "Athens",
    flag: "flags/gr.svg",
    colors: ["white","blue"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 68,
    name: "Grenada",
    iso: "gd",
    capital: "St. George's",
    flag: "flags/gd.svg",
    colors: ["red","yellow","green"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 69,
    name: "Guatemala",
    iso: "gt",
    capital: "Guatemala City",
    flag: "flags/gt.svg",
    colors: ["white","blue"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 70,
    name: "Guinea",
    iso: "gn",
    capital: "Conakry",
    flag: "flags/gn.svg",
    colors: ["red","yellow","green"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 71,
    name: "Guinea-Bissau",
    iso: "gw",
    capital: "Bissau",
    flag: "flags/gw.svg",
    colors: ["red","yellow","green","black"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 72,
    name: "Guyana",
    iso: "gy",
    capital: "Georgetown",
    flag: "flags/gy.svg",
    colors: ["red","yellow","green","black","white"],
    hasSymbol: true,
    continent: "south-america",
  },
  {
    id: 73,
    name: "Haiti",
    iso: "ht",
    capital: "Port-au-Prince",
    flag: "flags/ht.svg",
    colors: ["red","blue","green","yellow","white"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 74,
    name: "Vatican",
    iso: "va",
    capital: "Vatican City",
    flag: "flags/va.svg",
    colors: ["yellow","white"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 75,
    name: "Honduras",
    iso: "hn",
    capital: "Tegucigalpa",
    flag: "flags/hn.svg",
    colors: ["white","blue"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 76,
    name: "Hungary",
    iso: "hu",
    capital: "Budapest",
    flag: "flags/hu.svg",
    colors: ["red","green","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 77,
    name: "Iceland",
    iso: "is",
    capital: "Reykjavik",
    flag: "flags/is.svg",
    colors: ["red","blue","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 78,
    name: "India",
    iso: "in",
    capital: "New Delhi",
    flag: "flags/in.svg",
    colors: ["orange","green","white","blue"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 79,
    name: "Indonesia",
    iso: "id",
    capital: "Jakarta",
    flag: "flags/id.svg",
    colors: ["red","white"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 80,
    name: "Iran",
    iso: "ir",
    capital: "Tehran",
    flag: "flags/ir.svg",
    colors: ["red","green","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 81,
    name: "Iraq",
    iso: "iq",
    capital: "Baghdad",
    flag: "flags/iq.svg",
    colors: ["red","green","white","black"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 82,
    name: "Ireland",
    iso: "ie",
    capital: "Dublin",
    flag: "flags/ie.svg",
    colors: ["orange","green","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 83,
    name: "Israel",
    iso: "il",
    capital: "Jerusalem",
    flag: "flags/il.svg",
    colors: ["white","blue"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 84,
    name: "Italy",
    iso: "it",
    capital: "Rome",
    flag: "flags/it.svg",
    colors: ["green","white","red"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 85,
    name: "Jamaica",
    iso: "jm",
    capital: "Kingston",
    flag: "flags/jm.svg",
    colors: ["green","yellow","black"],
    hasSymbol: false,
    continent: "north-america",
  },
  {
    id: 86,
    name: "Japan",
    iso: "jp",
    capital: "Tokyo",
    flag: "flags/jp.svg",
    colors: ["white","red"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 87,
    name: "Jordan",
    iso: "jo",
    capital: "Amman",
    flag: "flags/jo.svg",
    colors: ["red","green","white","black"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 88,
    name: "Kazakhstan",
    iso: "kz",
    capital: "Astana",
    flag: "flags/kz.svg",
    colors: ["blue","gold"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 89,
    name: "Kenya",
    iso: "ke",
    capital: "Nairobi",
    flag: "flags/ke.svg",
    colors: ["black","red","green","white"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 90,
    name: "Kiribati",
    iso: "ki",
    capital: "South Tarawa",
    flag: "flags/ki.svg",
    colors: ["gold","red","blue","white"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 91,
    name: "Kosovo",
    iso: "xk",
    capital: "Pristina",
    flag: "flags/xk.svg",
    colors: ["gold","blue","white"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 92,
    name: "Kuwait",
    iso: "kw",
    capital: "Kuwait City",
    flag: "flags/kw.svg",
    colors: ["black","red","green","white"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 93,
    name: "Kyrgyzstan",
    iso: "kg",
    capital: "Bishkek",
    flag: "flags/kg.svg",
    colors: ["red","yellow"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 94,
    name: "Laos",
    iso: "la",
    capital: "Vientiane",
    flag: "flags/la.svg",
    colors: ["red","blue","white"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 95,
    name: "Latvia",
    iso: "lv",
    capital: "Riga",
    flag: "flags/lv.svg",
    colors: ["red","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 96,
    name: "Lebanon",
    iso: "lb",
    capital: "Beirut",
    flag: "flags/lb.svg",
    colors: ["red","white","green"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 97,
    name: "Lesotho",
    iso: "ls",
    capital: "Maseru",
    flag: "flags/ls.svg",
    colors: ["blue","white","green","black"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 98,
    name: "Liberia",
    iso: "lr",
    capital: "Monrovia",
    flag: "flags/lr.svg",
    colors: ["red","blue","white"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 99,
    name: "Libya",
    iso: "ly",
    capital: "Tripoli",
    flag: "flags/ly.svg",
    colors: ["red","black","green","white"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 100,
    name: "Liechtenstein",
    iso: "li",
    capital: "Vaduz",
    flag: "flags/li.svg",
    colors: ["red","blue","gold"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 101,
    name: "Lithuania",
    iso: "lt",
    capital: "Vilnius",
    flag: "flags/lt.svg",
    colors: ["red","green","yellow"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 102,
    name: "Luxembourg",
    iso: "lu",
    capital: "Luxembourg City",
    flag: "flags/lu.svg",
    colors: ["red","blue","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 103,
    name: "Madagascar",
    iso: "mg",
    capital: "Antananarivo",
    flag: "flags/mg.svg",
    colors: ["red","green","white"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 104,
    name: "Malawi",
    iso: "mw",
    capital: "Lilongwe",
    flag: "flags/mw.svg",
    colors: ["red","green","black"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 105,
    name: "Malaysia",
    iso: "my",
    capital: "Kuala Lumpur",
    flag: "flags/my.svg",
    colors: ["red","blue","white","yellow"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 106,
    name: "Maldives",
    iso: "mv",
    capital: "Malé",
    flag: "flags/mv.svg",
    colors: ["red","green","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 107,
    name: "Mali",
    iso: "ml",
    capital: "Bamako",
    flag: "flags/ml.svg",
    colors: ["red","green","yellow"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 108,
    name: "Malta",
    iso: "mt",
    capital: "Valletta",
    flag: "flags/mt.svg",
    colors: ["red","white"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 109,
    name: "Marshall Islands",
    iso: "mh",
    capital: "Majuro",
    flag: "flags/mh.svg",
    colors: ["blue","orange","white"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 110,
    name: "Mauritania",
    iso: "mr",
    capital: "Nouakchott",
    flag: "flags/mr.svg",
    colors: ["red","green","yellow"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 111,
    name: "Mauritius",
    iso: "mu",
    capital: "Port Louis",
    flag: "flags/mu.svg",
    colors: ["red","blue","green","yellow"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 112,
    name: "Mexico",
    iso: "mx",
    capital: "Mexico City",
    flag: "flags/mx.svg",
    colors: ["red","green","white"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 113,
    name: "Moldova",
    iso: "md",
    capital: "Chișinău",
    flag: "flags/md.svg",
    colors: ["blue","yellow","red"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 114,
    name: "Monaco",
    iso: "mc",
    capital: "Monaco",
    flag: "flags/mc.svg",
    colors: ["red","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 115,
    name: "Mongolia",
    iso: "mn",
    capital: "Ulaanbaatar",
    flag: "flags/mn.svg",
    colors: ["red","blue","yellow"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 116,
    name: "Montenegro",
    iso: "me",
    capital: "Podgorica",
    flag: "flags/me.svg",
    colors: ["red","gold"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 117,
    name: "Morocco",
    iso: "ma",
    capital: "Rabat",
    flag: "flags/ma.svg",
    colors: ["red","green"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 118,
    name: "Mozambique",
    iso: "mz",
    capital: "Maputo",
    flag: "flags/mz.svg",
    colors: ["red","green","black","yellow","white"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 119,
    name: "Myanmar",
    iso: "mm",
    capital: "Naypyidaw",
    flag: "flags/mm.svg",
    colors: ["red","green","yellow","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 120,
    name: "Namibia",
    iso: "na",
    capital: "Windhoek",
    flag: "flags/na.svg",
    colors: ["blue","red","green","yellow","white"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 121,
    name: "Nauru",
    iso: "nr",
    capital: "Yaren District",
    flag: "flags/nr.svg",
    colors: ["blue","gold","white"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 122,
    name: "Nepal",
    iso: "np",
    capital: "Kathmandu",
    flag: "flags/np.svg",
    colors: ["red","blue","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 123,
    name: "Netherlands",
    iso: "nl",
    capital: "Amsterdam",
    flag: "flags/nl.svg",
    colors: ["red","blue","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 124,
    name: "New Zealand",
    iso: "nz",
    capital: "Wellington",
    flag: "flags/nz.svg",
    colors: ["red","blue","white"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 125,
    name: "Nicaragua",
    iso: "ni",
    capital: "Managua",
    flag: "flags/ni.svg",
    colors: ["blue","white"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 126,
    name: "Niger",
    iso: "ne",
    capital: "Niamey",
    flag: "flags/ne.svg",
    colors: ["orange","green","white"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 127,
    name: "Nigeria",
    iso: "ng",
    capital: "Abuja",
    flag: "flags/ng.svg",
    colors: ["green","white"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 128,
    name: "North Korea",
    iso: "kp",
    capital: "Pyongyang",
    flag: "flags/kp.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 129,
    name: "North Macedonia",
    iso: "mk",
    capital: "Skopje",
    flag: "flags/mk.svg",
    colors: ["red","yellow"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 130,
    name: "Norway",
    iso: "no",
    capital: "Oslo",
    flag: "flags/no.svg",
    colors: ["red","blue","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 131,
    name: "Oman",
    iso: "om",
    capital: "Muscat",
    flag: "flags/om.svg",
    colors: ["red","green","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 132,
    name: "Pakistan",
    iso: "pk",
    capital: "Islamabad",
    flag: "flags/pk.svg",
    colors: ["green","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 133,
    name: "Palau",
    iso: "pw",
    capital: "Ngerulmud",
    flag: "flags/pw.svg",
    colors: ["blue","yellow"],
    hasSymbol: false,
    continent: "oceania",
  },
  {
    id: 134,
    name: "Panama",
    iso: "pa",
    capital: "Panama City",
    flag: "flags/pa.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 135,
    name: "Papua New Guinea",
    iso: "pg",
    capital: "Port Moresby",
    flag: "flags/pg.svg",
    colors: ["black","red","yellow"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 136,
    name: "Paraguay",
    iso: "py",
    capital: "Asunción",
    flag: "flags/py.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "south-america",
  },
  {
    id: 137,
    name: "Peru",
    iso: "pe",
    capital: "Lima",
    flag: "flags/pe.svg",
    colors: ["red","white"],
    hasSymbol: false,
    continent: "south-america",
  },
  {
    id: 138,
    name: "Philippines",
    iso: "ph",
    capital: "Manila",
    flag: "flags/ph.svg",
    colors: ["blue","red","white","gold"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 139,
    name: "Poland",
    iso: "pl",
    capital: "Warsaw",
    flag: "flags/pl.svg",
    colors: ["red","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 140,
    name: "Portugal",
    iso: "pt",
    capital: "Lisbon",
    flag: "flags/pt.svg",
    colors: ["green","red","yellow","white","blue"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 141,
    name: "Qatar",
    iso: "qa",
    capital: "Doha",
    flag: "flags/qa.svg",
    colors: ["white","maroon"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 142,
    name: "Republic of the Congo",
    iso: "cg",
    capital: "Brazzaville",
    flag: "flags/cg.svg",
    colors: ["green","red","yellow"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 143,
    name: "Romania",
    iso: "ro",
    capital: "Bucharest",
    flag: "flags/ro.svg",
    colors: ["blue","red","yellow"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 144,
    name: "Russia",
    iso: "ru",
    capital: "Moscow",
    flag: "flags/ru.svg",
    colors: ["blue","red","white"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 145,
    name: "Rwanda",
    iso: "rw",
    capital: "Kigali",
    flag: "flags/rw.svg",
    colors: ["blue","yellow","green"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 146,
    name: "Saint Kitts and Nevis",
    iso: "kn",
    capital: "Basseterre",
    flag: "flags/kn.svg",
    colors: ["green","black","red","white"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 147,
    name: "Saint Lucia",
    iso: "lc",
    capital: "Castries",
    flag: "flags/lc.svg",
    colors: ["blue","gold","white","black"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 148,
    name: "Saint Vincent and the Grenadines",
    iso: "vc",
    capital: "Kingstown",
    flag: "flags/vc.svg",
    colors: ["blue","yellow","green"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 149,
    name: "Samoa",
    iso: "ws",
    capital: "Apia",
    flag: "flags/ws.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 150,
    name: "San Marino",
    iso: "sm",
    capital: "San Marino",
    flag: "flags/sm.svg",
    colors: ["blue","white","gold","green"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 151,
    name: "Sao Tome and Principe",
    iso: "st",
    capital: "São Tomé",
    flag: "flags/st.svg",
    colors: ["green","red","yellow","black"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 152,
    name: "Saudi Arabia",
    iso: "sa",
    capital: "Riyadh",
    flag: "flags/sa.svg",
    colors: ["green","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 153,
    name: "Senegal",
    iso: "sn",
    capital: "Dakar",
    flag: "flags/sn.svg",
    colors: ["green","red","yellow"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 154,
    name: "Serbia",
    iso: "rs",
    capital: "Belgrade",
    flag: "flags/rs.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 155,
    name: "Seychelles",
    iso: "sc",
    capital: "Victoria",
    flag: "flags/sc.svg",
    colors: ["blue","red","white","yellow","green"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 156,
    name: "Sierra Leone",
    iso: "sl",
    capital: "Freetown",
    flag: "flags/sl.svg",
    colors: ["blue","green","white"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 157,
    name: "Singapore",
    iso: "sg",
    capital: "Singapore",
    flag: "flags/sg.svg",
    colors: ["red","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 158,
    name: "Slovakia",
    iso: "sk",
    capital: "Bratislava",
    flag: "flags/sk.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 159,
    name: "Slovenia",
    iso: "si",
    capital: "Ljubljana",
    flag: "flags/si.svg",
    colors: ["blue","red","white"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 160,
    name: "Solomon Islands",
    iso: "sb",
    capital: "Honiara",
    flag: "flags/sb.svg",
    colors: ["blue","green","white","yellow"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 161,
    name: "Somalia",
    iso: "so",
    capital: "Mogadishu",
    flag: "flags/so.svg",
    colors: ["blue","white"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 162,
    name: "South Africa",
    iso: "za",
    capital: "Pretoria",
    flag: "flags/za.svg",
    colors: ["green","black","red","white","blue"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 163,
    name: "South Korea",
    iso: "kr",
    capital: "Seoul",
    flag: "flags/kr.svg",
    colors: ["blue","black","red","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 164,
    name: "South Sudan",
    iso: "ss",
    capital: "Juba",
    flag: "flags/ss.svg",
    colors: ["green","black","red","white","blue","yellow"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 165,
    name: "Spain",
    iso: "es",
    capital: "Madrid",
    flag: "flags/es.svg",
    colors: ["red","yellow"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 166,
    name: "Sri Lanka",
    iso: "lk",
    capital: "Sri Jayawardenepura Kotte, Colombo",
    flag: "flags/lk.svg",
    colors: ["gold","green","orange","maroon"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 167,
    name: "State of Palestine",
    iso: "ps",
    capital: "Ramallah",
    flag: "flags/ps.svg",
    colors: ["red","black","white","green"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 168,
    name: "Sudan",
    iso: "sd",
    capital: "Khartoum",
    flag: "flags/sd.svg",
    colors: ["red","black","white","green"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 169,
    name: "Suriname",
    iso: "sr",
    capital: "Paramaribo",
    flag: "flags/sr.svg",
    colors: ["red","white","green","yellow"],
    hasSymbol: true,
    continent: "south-america",
  },
  {
    id: 170,
    name: "Sweden",
    iso: "se",
    capital: "Stockholm",
    flag: "flags/se.svg",
    colors: ["blue","yellow"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 171,
    name: "Switzerland",
    iso: "ch",
    capital: "Bern",
    flag: "flags/ch.svg",
    colors: ["red","white"],
    hasSymbol: true,
    continent: "europe",
  },
  {
    id: 172,
    name: "Syria",
    iso: "sy",
    capital: "Damascus",
    flag: "flags/sy.svg",
    colors: ["red","black","white","green"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 173,
    name: "Taiwan",
    iso: "tw",
    capital: "Taipei",
    flag: "flags/tw.svg",
    colors: ["red","blue","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 174,
    name: "Tajikistan",
    iso: "tj",
    capital: "Dushanbe",
    flag: "flags/tj.svg",
    colors: ["red","white","green","yellow"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 175,
    name: "Tanzania",
    iso: "tz",
    capital: "Dodoma",
    flag: "flags/tz.svg",
    colors: ["black","yellow","green","blue"],
    hasSymbol: false,
    continent: "africa",
  },
  {
    id: 176,
    name: "Thailand",
    iso: "th",
    capital: "Bangkok",
    flag: "flags/th.svg",
    colors: ["red","white","blue"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 177,
    name: "Timor-Leste",
    iso: "tl",
    capital: "Dili",
    flag: "flags/tl.svg",
    colors: ["red","black","white","yellow"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 178,
    name: "Togo",
    iso: "tg",
    capital: "Lomé",
    flag: "flags/tg.svg",
    colors: ["red","yellow","white","green"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 179,
    name: "Tonga",
    iso: "to",
    capital: "Nukuʻalofa",
    flag: "flags/to.svg",
    colors: ["red","white"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 180,
    name: "Trinidad and Tobago",
    iso: "tt",
    capital: "Port of Spain",
    flag: "flags/tt.svg",
    colors: ["red","black","white"],
    hasSymbol: false,
    continent: "south-america",
  },
  {
    id: 181,
    name: "Tunisia",
    iso: "tn",
    capital: "Tunis",
    flag: "flags/tn.svg",
    colors: ["red","white"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 182,
    name: "Turkmenistan",
    iso: "tm",
    capital: "Ashgabat",
    flag: "flags/tm.svg",
    colors: ["green","red","white","yellow"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 183,
    name: "Tuvalu",
    iso: "tv",
    capital: "Funafuti",
    flag: "flags/tv.svg",
    colors: ["blue","yellow","red","white"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 184,
    name: "Turkey",
    iso: "tr",
    capital: "Ankara",
    flag: "flags/tr.svg",
    colors: ["red","white"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 185,
    name: "Uganda",
    iso: "ug",
    capital: "Kampala",
    flag: "flags/ug.svg",
    colors: ["red","yellow","black"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 186,
    name: "Ukraine",
    iso: "ua",
    capital: "Kiev",
    flag: "flags/ua.svg",
    colors: ["blue","yellow"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 187,
    name: "United Arab Emirates",
    iso: "ae",
    capital: "Abu Dhabi",
    flag: "flags/ae.svg",
    colors: ["red","white","green","black"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 188,
    name: "United Kingdom",
    iso: "gb",
    capital: "London",
    flag: "flags/gb.svg",
    colors: ["red","white","blue"],
    hasSymbol: false,
    continent: "europe",
  },
  {
    id: 189,
    name: "United States of America",
    iso: "us",
    capital: "Washington, D.C.",
    flag: "flags/us.svg",
    colors: ["red","white","blue"],
    hasSymbol: true,
    continent: "north-america",
  },
  {
    id: 190,
    name: "Uruguay",
    iso: "uy",
    capital: "Montevideo",
    flag: "flags/uy.svg",
    colors: ["white","blue","yellow"],
    hasSymbol: true,
    continent: "south-america",
  },
  {
    id: 191,
    name: "Uzbekistan",
    iso: "uz",
    capital: "Tashkent",
    flag: "flags/uz.svg",
    colors: ["green","white","blue","red"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 192,
    name: "Vanuatu",
    iso: "vu",
    capital: "Port Vila",
    flag: "flags/vu.svg",
    colors: ["red","black","yellow","green"],
    hasSymbol: true,
    continent: "oceania",
  },
  {
    id: 193,
    name: "Venezuela",
    iso: "ve",
    capital: "Caracas",
    flag: "flags/ve.svg",
    colors: ["blue","red","yellow"],
    hasSymbol: true,
    continent: "south-america",
  },
  {
    id: 194,
    name: "Vietnam",
    iso: "vn",
    capital: "Hanoi",
    flag: "flags/vn.svg",
    colors: ["red","yellow"],
    hasSymbol: true,
    continent: "asia",
  },
  {
    id: 195,
    name: "Yemen",
    iso: "ye",
    capital: "Sana'a",
    flag: "flags/ye.svg",
    colors: ["red","white","black"],
    hasSymbol: false,
    continent: "asia",
  },
  {
    id: 196,
    name: "Zambia",
    iso: "zm",
    capital: "Lusaka",
    flag: "flags/zm.svg",
    colors: ["green","orange","red","black"],
    hasSymbol: true,
    continent: "africa",
  },
  {
    id: 197,
    name: "Zimbabwe",
    iso: "zw",
    capital: "Harare",
    flag: "flags/zw.svg",
    colors: ["green", "yellow", "red", "black","white"],
    hasSymbol: true,
    continent: "africa",
  },
];
