export const uniqueRegions = [
  {
    id: 2,
    countryName: "Aland Islands",
    independent: false,
    countryNamePt: "Ilhas Aland",
    capitalName: "Mariehamn",
    capitalNamePt: "Mariehamn",
    flag1x1: "flags/1x1/ax.svg",
    flag4x3: "flags/ax.svg",
    isoCode: "ax",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 5,
    countryName: "American Samoa",
    independent: false,
    countryNamePt: "Samoa Americana",
    capitalName: "Pago Pago",
    capitalNamePt: "Pago Pago",
    flag1x1: "flags/1x1/as.svg",
    flag4x3: "flags/as.svg",
    isoCode: "as",
    continentName: "Oceania",
    continentNamePt: "Oceânia",
  },
  {
    id: 8,
    countryName: "Anguilla",
    independent: false,
    countryNamePt: "Anguila",
    capitalName: "The Valley",
    capitalNamePt: "The Valley",
    flag1x1: "flags/1x1/ai.svg",
    flag4x3: "flags/ai.svg",
    isoCode: "ai",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 9,
    countryName: "Antarctica",
    independent: false,
    countryNamePt: "Antárctica",
    capitalName: "undefined",
    capitalNamePt: "indefinido",
    flag1x1: "flags/1x1/aq.svg",
    flag4x3: "flags/aq.svg",
    isoCode: "aq",
    continentName: "Antarctica",
    continentNamePt: "Antártida",
  },
  {
    id: 13,
    countryName: "Aruba",
    independent: false,
    countryNamePt: "Aruba",
    capitalName: "Oranjestad",
    capitalNamePt: "Oranjestad",
    flag1x1: "flags/1x1/aw.svg",
    flag4x3: "flags/aw.svg",
    isoCode: "aw",
    continentName: "South America",
    continentNamePt: "América do Sul",
  },
  {
    id: 25,
    countryName: "Bermuda",
    independent: false,
    countryNamePt: "Bermudas",
    capitalName: "Hamilton",
    capitalNamePt: "Hamilton",
    flag1x1: "flags/1x1/bm.svg",
    flag4x3: "flags/bm.svg",
    isoCode: "bm",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 32,
    countryName: "British Indian Ocean Territory",
    independent: false,
    countryNamePt: "Território Britânico do Oceano Índico",
    capitalName: "Diego Garcia",
    capitalNamePt: "Diego Garcia",
    flag1x1: "flags/1x1/io.svg",
    flag4x3: "flags/io.svg",
    isoCode: "io",
    continentName: "Asia",
    continentNamePt: "Ásia",
  },
  {
    id: 41,
    countryName: "Canary Islands",
    independent: false,
    countryNamePt: "Ilhas Canárias",
    capitalName: "undefined",
    capitalNamePt: "indefinido",
    flag1x1: "flags/1x1/ic.svg",
    flag4x3: "flags/ic.svg",
    isoCode: "ic",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 42,
    countryName: "Cayman Islands",
    independent: false,
    countryNamePt: "Ilhas Caimão",
    capitalName: "George Town",
    capitalNamePt: "George Town",
    flag1x1: "flags/1x1/ky.svg",
    flag4x3: "flags/ky.svg",
    isoCode: "ky",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 47,
    countryName: "Christmas Island",
    independent: false,
    countryNamePt: "Ilha do Natal",
    capitalName: "Flying Fish Cove",
    capitalNamePt: "Flying Fish Cove",
    flag1x1: "flags/1x1/cx.svg",
    flag4x3: "flags/cx.svg",
    isoCode: "cx",
    continentName: "Asia",
    continentNamePt: "Ásia",
  },
  {
    id: 48,
    countryName: "Cocos (Keeling) Islands",
    independent: false,
    countryNamePt: "Ilhas Cocos (Keeling)",
    capitalName: "West Island",
    capitalNamePt: "Ilha Ocidental",
    flag1x1: "flags/1x1/cc.svg",
    flag4x3: "flags/cc.svg",
    isoCode: "cc",
    continentName: "Asia",
    continentNamePt: "Ásia",
  },
  {
    id: 51,
    countryName: "Cook Islands",
    independent: false,
    countryNamePt: "Ilhas Cook",
    capitalName: "Avarua",
    capitalNamePt: "Avarua",
    flag1x1: "flags/1x1/ck.svg",
    flag4x3: "flags/ck.svg",
    isoCode: "ck",
    continentName: "Oceania",
    continentNamePt: "Oceânia",
  },
  {
    id: 55,
    countryName: "Curaçao",
    independent: false,
    countryNamePt: "Curaçau",
    capitalName: "Willemstad",
    capitalNamePt: "Willemstad",
    flag1x1: "flags/1x1/cw.svg",
    flag4x3: "flags/cw.svg",
    isoCode: "cw",
    continentName: "South America",
    continentNamePt: "América do Sul",
  },
  {
    id: 67,
    countryName: "England",
    independent: false,
    countryNamePt: "Inglaterra",
    capitalName: "London",
    capitalNamePt: "Londres",
    flag1x1: "flags/1x1/gb-eng.svg",
    flag4x3: "flags/gb-eng.svg",
    isoCode: "gb-eng",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 73,
    countryName: "Europe",
    independent: false,
    countryNamePt: "Europa",
    capitalName: "undefined",
    capitalNamePt: "indefinido",
    flag1x1: "flags/1x1/eu.svg",
    flag4x3: "flags/eu.svg",
    isoCode: "eu",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 74,
    countryName: "Falkland Islands",
    independent: false,
    countryNamePt: "Ilhas Malvinas",
    capitalName: "Stanley",
    capitalNamePt: "Stanley",
    flag1x1: "flags/1x1/fk.svg",
    flag4x3: "flags/fk.svg",
    isoCode: "fk",
    continentName: "South America",
    continentNamePt: "América do Sul",
  },
  {
    id: 75,
    countryName: "Faroe Islands",
    independent: false,
    countryNamePt: "Ilhas Faroé",
    capitalName: "Tórshavn",
    capitalNamePt: "Tórshavn",
    flag1x1: "flags/1x1/fo.svg",
    flag4x3: "flags/fo.svg",
    isoCode: "fo",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 81,
    countryName: "French Polynesia",
    independent: false,
    countryNamePt: "Polinésia Francesa",
    capitalName: "Papeete",
    capitalNamePt: "Papete",
    flag1x1: "flags/1x1/pf.svg",
    flag4x3: "flags/pf.svg",
    isoCode: "pf",
    continentName: "Oceania",
    continentNamePt: "Oceânia",
  },
  {
    id: 87,
    countryName: "Gibraltar",
    independent: false,
    countryNamePt: "Gibraltar",
    capitalName: "Gibraltar",
    capitalNamePt: "Gibraltar",
    flag1x1: "flags/1x1/gi.svg",
    flag4x3: "flags/gi.svg",
    isoCode: "gi",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 89,
    countryName: "Greenland",
    independent: false,
    countryNamePt: "Gronelândia",
    capitalName: "Nuuk",
    capitalNamePt: "Nuuk",
    flag1x1: "flags/1x1/gl.svg",
    flag4x3: "flags/gl.svg",
    isoCode: "gl",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 92,
    countryName: "Guam",
    independent: false,
    countryNamePt: "Guam",
    capitalName: "Hagåtña",
    capitalNamePt: "Agana",
    flag1x1: "flags/1x1/gu.svg",
    flag4x3: "flags/gu.svg",
    isoCode: "gu",
    continentName: "Oceania",
    continentNamePt: "Oceânia",
  },
  {
    id: 94,
    countryName: "Guernsey",
    independent: false,
    countryNamePt: "Guernsey",
    capitalName: "Saint Peter Port",
    capitalNamePt: "Porto de São Pedro",
    flag1x1: "flags/1x1/gg.svg",
    flag4x3: "flags/gg.svg",
    isoCode: "gg",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 101,
    countryName: "Hong Kong",
    independent: false,
    countryNamePt: "Hong Kong",
    capitalName: "Hong Kong",
    capitalNamePt: "Hong Kong",
    flag1x1: "flags/1x1/hk.svg",
    flag4x3: "flags/hk.svg",
    isoCode: "hk",
    continentName: "Asia",
    continentNamePt: "Ásia",
  },
  {
    id: 109,
    countryName: "Isle of Man",
    independent: false,
    countryNamePt: "Ilha de Man",
    capitalName: "Douglas",
    capitalNamePt: "Douglas",
    flag1x1: "flags/1x1/im.svg",
    flag4x3: "flags/im.svg",
    isoCode: "im",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 114,
    countryName: "Jersey",
    independent: false,
    countryNamePt: "Jersey",
    capitalName: "Saint Helier",
    capitalNamePt: "Saint Helier",
    flag1x1: "flags/1x1/je.svg",
    flag4x3: "flags/je.svg",
    isoCode: "je",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 131,
    countryName: "Macau",
    independent: false,
    countryNamePt: "Macau",
    capitalName: "Macau",
    capitalNamePt: "Macau",
    flag1x1: "flags/1x1/mo.svg",
    flag4x3: "flags/mo.svg",
    isoCode: "mo",
    continentName: "Asia",
    continentNamePt: "Ásia",
  },
  {
    id: 133,
    countryName: "Madeira Islands",
    independent: false,
    countryNamePt: "Arquipélago da Madeira",
    capitalName: "Funchal",
    capitalNamePt: "Funchal",
    flag1x1: "flags/1x1/mad.svg",
    flag4x3: "flags/mad.svg",
    isoCode: "mad",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 140,
    countryName: "Martinique",
    independent: false,
    countryNamePt: "Martinica",
    capitalName: "Fort-de-France",
    capitalNamePt: "Forte de França",
    flag1x1: "flags/1x1/mq.svg",
    flag4x3: "flags/mq.svg",
    isoCode: "mq",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 149,
    countryName: "Montserrat",
    independent: false,
    countryNamePt: "Monserrate",
    capitalName: "Braids",
    capitalNamePt: "Brades",
    flag1x1: "flags/1x1/ms.svg",
    flag4x3: "flags/ms.svg",
    isoCode: "ms",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 157,
    countryName: "New Caledonia",
    independent: false,
    countryNamePt: "Nova Caledónia",
    capitalName: "Nouméa",
    capitalNamePt: "Noumea",
    flag1x1: "flags/1x1/nc.svg",
    flag4x3: "flags/nc.svg",
    isoCode: "nc",
    continentName: "Oceania",
    continentNamePt: "Oceânia",
  },
  {
    id: 162,
    countryName: "Niue",
    independent: false,
    countryNamePt: "Niuê",
    capitalName: "Alofi",
    capitalNamePt: "Alofi",
    flag1x1: "flags/1x1/nu.svg",
    flag4x3: "flags/nu.svg",
    isoCode: "nu",
    continentName: "Oceania",
    continentNamePt: "Oceânia",
  },
  {
    id: 163,
    countryName: "Norfolk Island",
    independent: false,
    countryNamePt: "Ilha Norfolk",
    capitalName: "Kingston",
    capitalNamePt: "Kingston",
    flag1x1: "flags/1x1/nf.svg",
    flag4x3: "flags/nf.svg",
    isoCode: "nf",
    continentName: "Oceania",
    continentNamePt: "Oceânia",
  },
  {
    id: 166,
    countryName: "Northern Ireland",
    independent: false,
    countryNamePt: "Irlanda do Norte",
    capitalName: "Belfast",
    capitalNamePt: "Belfast",
    flag1x1: "flags/1x1/gb-nir.svg",
    flag4x3: "flags/gb-nir.svg",
    isoCode: "gb-nir",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 167,
    countryName: "Northern Mariana Islands",
    independent: false,
    countryNamePt: "Ilhas Marianas do Norte",
    capitalName: "Saipan",
    capitalNamePt: "Saipan",
    flag1x1: "flags/1x1/mp.svg",
    flag4x3: "flags/mp.svg",
    isoCode: "mp",
    continentName: "Oceania",
    continentNamePt: "Oceânia",
  },
  {
    id: 177,
    countryName: "Pitcairn",
    independent: false,
    countryNamePt: "Ilhas Pitcairn",
    capitalName: "Adamstown",
    capitalNamePt: "Adamstown",
    flag1x1: "flags/1x1/pn.svg",
    flag4x3: "flags/pn.svg",
    isoCode: "pn",
    continentName: "Oceania",
    continentNamePt: "Oceânia",
  },
  {
    id: 180,
    countryName: "Puerto Rico",
    independent: false,
    countryNamePt: "Porto Rico",
    capitalName: "San Juan",
    capitalNamePt: "São João",
    flag1x1: "flags/1x1/pr.svg",
    flag4x3: "flags/pr.svg",
    isoCode: "pr",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 187,
    countryName: "Saint Helena",
    independent: false,
    countryNamePt: "Santa Helena",
    capitalName: "Jamestown",
    capitalNamePt: "Jamestown",
    flag1x1: "flags/1x1/sh-hl.svg",
    flag4x3: "flags/sh-hl.svg",
    isoCode: "sh-hl",
    continentName: "Africa",
    continentNamePt: "África",
  },
  {
    id: 195,
    countryName: "Scotland",
    independent: false,
    countryNamePt: "Escócia",
    capitalName: "Edinburgh",
    capitalNamePt: "Edimburgo",
    flag1x1: "flags/1x1/gb-sct.svg",
    flag4x3: "flags/gb-sct.svg",
    isoCode: "gb-sct",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 201,
    countryName: "Sint Maarten",
    independent: false,
    countryNamePt: "São Martinho",
    capitalName: "Philipsburg",
    capitalNamePt: "Philipsburg",
    flag1x1: "flags/1x1/sx.svg",
    flag4x3: "flags/sx.svg",
    isoCode: "sx",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 223,
    countryName: "Tokelau",
    independent: false,
    countryNamePt: "Toquelau",
    capitalName: "Nukunonu",
    capitalNamePt: "Nucunonu",
    flag1x1: "flags/1x1/tk.svg",
    flag4x3: "flags/tk.svg",
    isoCode: "tk",
    continentName: "Oceania",
    continentNamePt: "Oceânia",
  },
  {
    id: 226,
    countryName: "Tristan da Cunha",
    independent: false,
    countryNamePt: "Tristão da Cunha",
    capitalName: "Edinburgh of the Seven Seas",
    capitalNamePt: "Edimburgo dos Sete Mares",
    flag1x1: "flags/1x1/sh-ta.svg",
    flag4x3: "flags/sh-ta.svg",
    isoCode: "sh-ta",
    continentName: "Africa",
    continentNamePt: "África",
  },
  {
    id: 229,
    countryName: "Turks and Caicos Islands",
    independent: false,
    countryNamePt: "Ilhas Turcas e Caicos",
    capitalName: "Cockburn Town",
    capitalNamePt: "Cidade de Cockburn",
    flag1x1: "flags/1x1/tc.svg",
    flag4x3: "flags/tc.svg",
    isoCode: "tc",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 236,
    countryName: "United Nations",
    independent: false,
    countryNamePt: "Nações Unidas",
    capitalName: "undefined",
    capitalNamePt: "indefinido",
    flag1x1: "flags/1x1/un.svg",
    flag4x3: "flags/un.svg",
    isoCode: "un",
    continentName: "undefined",
    continentNamePt: "undefined",
  },
  {
    id: 243,
    countryName: "Virgin Islands (British)",
    independent: false,
    countryNamePt: "Ilhas Virgens (Britânicas)",
    capitalName: "Road Town",
    capitalNamePt: "Road Town",
    flag1x1: "flags/1x1/vg.svg",
    flag4x3: "flags/vg.svg",
    isoCode: "vg",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 244,
    countryName: "Virgin Islands (U.S.)",
    independent: false,
    countryNamePt: "Ilhas Virgens (EUA)",
    capitalName: "Charlotte Amalie",
    capitalNamePt: "Charlotte Amalie",
    flag1x1: "flags/1x1/vi.svg",
    flag4x3: "flags/vi.svg",
    isoCode: "vi",
    continentName: "North America",
    continentNamePt: "América do Norte",
  },
  {
    id: 245,
    countryName: "Wales",
    independent: false,
    countryNamePt: "País de Gales",
    capitalName: "Cardiff",
    capitalNamePt: "Cardiff",
    flag1x1: "flags/1x1/gb-wls.svg",
    flag4x3: "flags/gb-wls.svg",
    isoCode: "gb-wls",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 246,
    countryName: "Azores Island",
    independent: false,
    countryNamePt: "Arquipélago dos Açores",
    capitalName: "Ponta Delgada",
    capitalNamePt: "Ponta Delgada",
    flag1x1: "flags/1x1/azo.svg",
    flag4x3: "flags/azo.svg",
    isoCode: "azo",
    continentName: "Europe",
    continentNamePt: "Europa",
  },
  {
    id: 247,
    countryName: "Western Sahara",
    independent: false,
    countryNamePt: "Saara Ocidental",
    capitalName: "Laayoune",
    capitalNamePt: "El Aiune",
    flag1x1: "flags/1x1/eh.svg",
    flag4x3: "flags/eh.svg",
    isoCode: "eh",
    continentName: "Africa",
    continentNamePt: "África",
  },
];