export const updatedUniqueRegions = [
  {
    id: 2,
    name: "Aland Islands",
    isCountry: false,
    capital: "Mariehamn",
    flag: "flags/ax.svg",
    iso: "ax",
    continent: "europe",
  },
  {
    id: 5,
    name: "American Samoa",
    isCountry: false,
    capital: "Pago Pago",
    flag: "flags/as.svg",
    iso: "as",
    continent: "oceania",
  },
  {
    id: 8,
    name: "Anguilla",
    isCountry: false,
    capital: "The Valley",
    flag: "flags/ai.svg",
    iso: "ai",
    continent: "north-america",
  },
  {
    id: 9,
    name: "antarctica",
    isCountry: false,
    capital: "undefined",
    flag: "flags/aq.svg",
    iso: "aq",
    continent: "antarctica",
  },
  {
    id: 13,
    name: "Aruba",
    isCountry: false,
    capital: "Oranjestad",
    flag: "flags/aw.svg",
    iso: "aw",
    continent: "south-america",
  },
  {
    id: 25,
    name: "Bermuda",
    isCountry: false,
    capital: "Hamilton",
    flag: "flags/bm.svg",
    iso: "bm",
    continent: "north-america",
  },
  {
    id: 32,
    name: "British Indian Ocean Territory",
    isCountry: false,
    capital: "Diego Garcia",
    flag: "flags/io.svg",
    iso: "io",
    continent: "asia",
  },
  {
    id: 41,
    name: "Canary Islands",
    isCountry: false,
    capital: "undefined",
    flag: "flags/ic.svg",
    iso: "ic",
    continent: "europe",
  },
  {
    id: 42,
    name: "Cayman Islands",
    isCountry: false,
    capital: "George Town",
    flag: "flags/ky.svg",
    iso: "ky",
    continent: "north-america",
  },
  {
    id: 47,
    name: "Christmas Island",
    isCountry: false,
    capital: "Flying Fish Cove",
    flag: "flags/cx.svg",
    iso: "cx",
    continent: "asia",
  },
  {
    id: 48,
    name: "Cocos (Keeling) Islands",
    isCountry: false,
    capital: "West Island",
    flag: "flags/cc.svg",
    iso: "cc",
    continent: "asia",
  },
  {
    id: 51,
    name: "Cook Islands",
    isCountry: false,
    capital: "Avarua",
    flag: "flags/ck.svg",
    iso: "ck",
    continent: "oceania",
  },
  {
    id: 55,
    name: "Curaçao",
    isCountry: false,
    capital: "Willemstad",
    flag: "flags/cw.svg",
    iso: "cw",
    continent: "south-america",
  },
  {
    id: 67,
    name: "England",
    isCountry: false,
    capital: "London",
    flag: "flags/gb-eng.svg",
    iso: "gb-eng",
    continent: "europe",
  },
  {
    id: 73,
    name: "europe",
    isCountry: false,
    capital: "undefined",
    flag: "flags/eu.svg",
    iso: "eu",
    continent: "europe",
  },
  {
    id: 74,
    name: "Falkland Islands",
    isCountry: false,
    capital: "Stanley",
    flag: "flags/fk.svg",
    iso: "fk",
    continent: "south-america",
  },
  {
    id: 75,
    name: "Faroe Islands",
    isCountry: false,
    capital: "Tórshavn",
    flag: "flags/fo.svg",
    iso: "fo",
    continent: "europe",
  },
  {
    id: 81,
    name: "French Polynesia",
    isCountry: false,
    capital: "Papeete",
    flag: "flags/pf.svg",
    iso: "pf",
    continent: "oceania",
  },
  {
    id: 87,
    name: "Gibraltar",
    isCountry: false,
    capital: "Gibraltar",
    flag: "flags/gi.svg",
    iso: "gi",
    continent: "europe",
  },
  {
    id: 89,
    name: "Greenland",
    isCountry: false,
    capital: "Nuuk",
    flag: "flags/gl.svg",
    iso: "gl",
    continent: "north-america",
  },
  {
    id: 92,
    name: "Guam",
    isCountry: false,
    capital: "Hagåtña",
    flag: "flags/gu.svg",
    iso: "gu",
    continent: "oceania",
  },
  {
    id: 94,
    name: "Guernsey",
    isCountry: false,
    capital: "Saint Peter Port",
    flag: "flags/gg.svg",
    iso: "gg",
    continent: "europe",
  },
  {
    id: 101,
    name: "Hong Kong",
    isCountry: false,
    capital: "Hong Kong",
    flag: "flags/hk.svg",
    iso: "hk",
    continent: "asia",
  },
  {
    id: 109,
    name: "Isle of Man",
    isCountry: false,
    capital: "Douglas",
    flag: "flags/im.svg",
    iso: "im",
    continent: "europe",
  },
  {
    id: 114,
    name: "Jersey",
    isCountry: false,
    capital: "Saint Helier",
    flag: "flags/je.svg",
    iso: "je",
    continent: "europe",
  },
  {
    id: 131,
    name: "Macau",
    isCountry: false,
    capital: "Macau",
    flag: "flags/mo.svg",
    iso: "mo",
    continent: "asia",
  },
  {
    id: 133,
    name: "Madeira Islands",
    isCountry: false,
    capital: "Funchal",
    flag: "flags/mad.svg",
    iso: "mad",
    continent: "europe",
  },
  {
    id: 140,
    name: "Martinique",
    isCountry: false,
    capital: "Fort-de-France",
    flag: "flags/mq.svg",
    iso: "mq",
    continent: "north-america",
  },
  {
    id: 149,
    name: "Montserrat",
    isCountry: false,
    capital: "Braids",
    flag: "flags/ms.svg",
    iso: "ms",
    continent: "north-america",
  },
  {
    id: 157,
    name: "New Caledonia",
    isCountry: false,
    capital: "Nouméa",
    flag: "flags/nc.svg",
    iso: "nc",
    continent: "oceania",
  },
  {
    id: 162,
    name: "Niue",
    isCountry: false,
    capital: "Alofi",
    flag: "flags/nu.svg",
    iso: "nu",
    continent: "oceania",
  },
  {
    id: 163,
    name: "Norfolk Island",
    isCountry: false,
    capital: "Kingston",
    flag: "flags/nf.svg",
    iso: "nf",
    continent: "oceania",
  },
  {
    id: 166,
    name: "Northern Ireland",
    isCountry: false,
    capital: "Belfast",
    flag: "flags/gb-nir.svg",
    iso: "gb-nir",
    continent: "europe",
  },
  {
    id: 167,
    name: "Northern Mariana Islands",
    isCountry: false,
    capital: "Saipan",
    flag: "flags/mp.svg",
    iso: "mp",
    continent: "oceania",
  },
  {
    id: 177,
    name: "Pitcairn",
    isCountry: false,
    capital: "Adamstown",
    flag: "flags/pn.svg",
    iso: "pn",
    continent: "oceania",
  },
  {
    id: 180,
    name: "Puerto Rico",
    isCountry: false,
    capital: "San Juan",
    flag: "flags/pr.svg",
    iso: "pr",
    continent: "north-america",
  },
  {
    id: 187,
    name: "Saint Helena",
    isCountry: false,
    capital: "Jamestown",
    flag: "flags/sh-hl.svg",
    iso: "sh-hl",
    continent: "africa",
  },
  {
    id: 195,
    name: "Scotland",
    isCountry: false,
    capital: "Edinburgh",
    flag: "flags/gb-sct.svg",
    iso: "gb-sct",
    continent: "europe",
  },
  {
    id: 201,
    name: "Sint Maarten",
    isCountry: false,
    capital: "Philipsburg",
    flag: "flags/sx.svg",
    iso: "sx",
    continent: "north-america",
  },
  {
    id: 223,
    name: "Tokelau",
    isCountry: false,
    capital: "Nukunonu",
    flag: "flags/tk.svg",
    iso: "tk",
    continent: "oceania",
  },
  {
    id: 226,
    name: "Tristan da Cunha",
    isCountry: false,
    capital: "Edinburgh of the Seven Seas",
    flag: "flags/sh-ta.svg",
    iso: "sh-ta",
    continent: "africa",
  },
  {
    id: 229,
    name: "Turks and Caicos Islands",
    isCountry: false,
    capital: "Cockburn Town",
    flag: "flags/tc.svg",
    iso: "tc",
    continent: "north-america",
  },
  {
    id: 236,
    name: "United Nations",
    isCountry: false,
    capital: "undefined",
    flag: "flags/un.svg",
    iso: "un",
    continent: "undefined",
  },
  {
    id: 243,
    name: "Virgin Islands (British)",
    isCountry: false,
    capital: "Road Town",
    flag: "flags/vg.svg",
    iso: "vg",
    continent: "north-america",
  },
  {
    id: 244,
    name: "Virgin Islands (U.S.)",
    isCountry: false,
    capital: "Charlotte Amalie",
    flag: "flags/vi.svg",
    iso: "vi",
    continent: "north-america",
  },
  {
    id: 245,
    name: "Wales",
    isCountry: false,
    capital: "Cardiff",
    flag: "flags/gb-wls.svg",
    iso: "gb-wls",
    continent: "europe",
  },
  {
    id: 246,
    name: "Azores Islands",
    isCountry: false,
    capital: "Ponta Delgada",
    flag: "flags/azo.svg",
    iso: "azo",
    continent: "europe",
  },
  {
    id: 247,
    name: "Western Sahara",
    isCountry: false,
    capital: "Laayoune",
    flag: "flags/eh.svg",
    iso: "eh",
    continent: "africa",
  },
];